version: "3.6"
services:
    db:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --ssl-ca=/etc/mysql/ssl/ca.pem --ssl-cert=/etc/mysql/ssl/server-cert.pem --ssl-key=/etc/mysql/ssl/server-key.pem --require_secure_transport=ON 
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret6
            - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
        volumes:
            - ./certs:/etc/mysql/ssl:ro
            - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro

    python-app:
        build: ./project
        depends_on:
            - db
        container_name: python_container
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    web:
        build: ./project
        ports:
            - "8080:80"    
        environment:
            - FLASK_ENV=development